# Generated by Django 4.0.3 on 2022-04-02 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(2)])),
                ('sport', models.CharField(choices=[('Football', 'Football'), ('Volleyball', 'Volleyball'), ('Tennis', 'Tennis'), ('Swimming', 'Swimming'), ('Athletics', 'Athletics')], max_length=10)),
                ('information', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(1)])),
                ('last_name', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(1)])),
                ('date_of_birth', models.DateField()),
                ('date_time_of_joining', models.DateTimeField(auto_now_add=True)),
                ('clubs', models.ManyToManyField(to='web.club')),
            ],
        ),
    ]
