# Generated by Django 4.0.3 on 2022-04-02 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
