# Generated by Django 4.0.3 on 2022-04-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
