# Generated by Django 4.0.3 on 2022-04-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_contacts_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('type', models.CharField(choices=[('Game', 'Game'), ('Celebration', 'Celebration'), ('Tournament', 'Tournament'), ('Meet the team', 'Meet the team')], max_length=13)),
            ],
        ),
    ]
