# Generated by Django 4.0.3 on 2022-04-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_event_alter_player_first_name_alter_player_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day_and_time',
            field=models.CharField(choices=[('Monday at 19:00', 'Monday at 19:00'), ('Wednesday at 12:00', 'Wednesday at 12:00'), ('Wednesday at 19:00', 'Wednesday at 19:00'), ('Friday at 19:00', 'Friday at 19:00'), ('Saturday at 10:00', 'Saturday at 10:00'), ('Saturday at 20:00', 'Saturday at 20:00'), ('Sunday at 20:00', 'Sunday at 20:00')], max_length=18),
        ),
    ]
