# Generated by Django 4.0.3 on 2022-04-09 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 21, 2, 25, 100159)),
        ),
        migrations.AddField(
            model_name='event',
            name='information',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
