# Generated by Django 4.0.3 on 2022-04-09 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_event_day_time_event_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 21, 5, 35, 144850)),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
