# Generated by Django 4.0.3 on 2022-04-09 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_event_day_time_alter_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('Arena Sportium', 'Arena Sportium'), ('Ceremony hall - Arena Sportium', 'Ceremony hall - Arena Sportium'), ('The garden next to Sportium Stadium', 'The garden next to Sportium Stadium')], default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='day_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 21, 16, 9, 932332)),
        ),
    ]
