# Generated by Django 4.0.3 on 2022-04-09 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_event_location_alter_event_day_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 21, 18, 37, 861577)),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('Arena Sportium', 'Arena Sportium'), ('Ceremony hall - Arena Sportium', 'Ceremony hall - Arena Sportium'), ('The garden next to Sportium Stadium', 'The garden next to Sportium Stadium'), ('Sportium Stadium', 'Sportium Stadium'), ('Tennis club Sportium', 'Tennis club Sportium'), ('Swimming pool Sportium', 'Swimming pool Sportium')], max_length=35),
        ),
    ]
