# Generated by Django 4.0.3 on 2022-03-27 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='information',
            new_name='personal_information',
        ),
    ]
