# Generated by Django 4.0.3 on 2022-04-14 17:13

import django.core.validators
from django.db import migrations, models
import sportium.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(1), sportium.common.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(1), sportium.common.validators.validate_only_letters]),
        ),
    ]
